; Installer texts (English / Russian / Romanian)

LangString T_TYPE_TITLE ${LANG_ENGLISH} "How do you want to use RenderBatch?"
LangString T_TYPE_SUB ${LANG_ENGLISH} "Install it on this PC, or keep it all in one folder."
LangString T_INSTALL ${LANG_ENGLISH} "Install on this PC (recommended)"
LangString T_INSTALL_D ${LANG_ENGLISH} "Into your user folder, no admin rights needed. Start menu and desktop shortcuts, and an uninstaller in Windows Settings > Apps."
LangString T_PORTABLE ${LANG_ENGLISH} "Portable"
LangString T_PORTABLE_D ${LANG_ENGLISH} "Everything in one folder you choose (also a USB drive). Nothing is written outside it; to remove it, delete the folder or run its Uninstall.exe."
LangString T_DESKTOP ${LANG_ENGLISH} "Desktop shortcut"
LangString T_STARTMENU ${LANG_ENGLISH} "Start menu shortcut"
LangString T_EXISTING ${LANG_ENGLISH} "Already installed: RenderBatch"
LangString T_DIR_P_TITLE ${LANG_ENGLISH} "Portable folder"
LangString T_DIR_P_SUB ${LANG_ENGLISH} "Choose the folder that will hold RenderBatch with its settings, presets and models."
LangString T_NOWRITE ${LANG_ENGLISH} "RenderBatch can't write to this folder without admin rights, and it keeps its settings in its own folder. Choose a folder in your user folder or on another drive (e.g. D:\RenderBatch)."
LangString T_RUNNING ${LANG_ENGLISH} "RenderBatch is running. Close it, then click Retry."
LangString T_COPYING ${LANG_ENGLISH} "Copying the app..."
LangString T_FINISHING ${LANG_ENGLISH} "Finishing setup: getting the Python packages and models (downloads about 250 MB if they aren't on this PC)..."
LangString T_SETUP_LATER ${LANG_ENGLISH} "RenderBatch is installed, but its Python packages and models couldn't be downloaded (no internet connection?). Start RenderBatch when you're online: it finishes the setup then."
LangString T_RUN ${LANG_ENGLISH} "Start RenderBatch"
LangString T_DEL_MINE ${LANG_ENGLISH} "Also delete your settings, presets, looks, LUTs and models in this folder?$\r$\n$\r$\nNo = keep them (a later install in the same folder uses them again)."

LangString T_TYPE_TITLE ${LANG_RUSSIAN} "Как вы хотите использовать RenderBatch?"
LangString T_TYPE_SUB ${LANG_RUSSIAN} "Установить на этот ПК или держать всё в одной папке."
LangString T_INSTALL ${LANG_RUSSIAN} "Установить на этот ПК (рекомендуется)"
LangString T_INSTALL_D ${LANG_RUSSIAN} "В папку пользователя, права администратора не нужны. Ярлыки в меню «Пуск» и на рабочем столе, удаление через «Параметры Windows» > «Приложения»."
LangString T_PORTABLE ${LANG_RUSSIAN} "Портативно"
LangString T_PORTABLE_D ${LANG_RUSSIAN} "Всё в одной выбранной папке (можно и на флешке). Вне её ничего не записывается; чтобы удалить, удалите папку или запустите её Uninstall.exe."
LangString T_DESKTOP ${LANG_RUSSIAN} "Ярлык на рабочем столе"
LangString T_STARTMENU ${LANG_RUSSIAN} "Ярлык в меню «Пуск»"
LangString T_EXISTING ${LANG_RUSSIAN} "Уже установлено: RenderBatch"
LangString T_DIR_P_TITLE ${LANG_RUSSIAN} "Портативная папка"
LangString T_DIR_P_SUB ${LANG_RUSSIAN} "Выберите папку, в которой будут RenderBatch, его настройки, пресеты и модели."
LangString T_NOWRITE ${LANG_RUSSIAN} "RenderBatch не может писать в эту папку без прав администратора, а свои настройки он хранит в своей папке. Выберите папку в папке пользователя или на другом диске (например, D:\RenderBatch)."
LangString T_RUNNING ${LANG_RUSSIAN} "RenderBatch запущен. Закройте его и нажмите «Повтор»."
LangString T_COPYING ${LANG_RUSSIAN} "Копирование программы..."
LangString T_FINISHING ${LANG_RUSSIAN} "Завершение установки: получение пакетов Python и моделей (если их нет на этом ПК, скачивается около 250 МБ)..."
LangString T_SETUP_LATER ${LANG_RUSSIAN} "RenderBatch установлен, но пакеты Python и модели не удалось скачать (нет интернета?). Запустите RenderBatch, когда будете в сети: он завершит установку."
LangString T_RUN ${LANG_RUSSIAN} "Запустить RenderBatch"
LangString T_DEL_MINE ${LANG_RUSSIAN} "Удалить также ваши настройки, пресеты, образы, LUT и модели в этой папке?$\r$\n$\r$\nНет = сохранить (при новой установке в ту же папку они снова будут использованы)."

LangString T_TYPE_TITLE ${LANG_ROMANIAN} "Cum vrei să folosești RenderBatch?"
LangString T_TYPE_SUB ${LANG_ROMANIAN} "Instalează-l pe acest PC sau păstrează totul într-un singur folder."
LangString T_INSTALL ${LANG_ROMANIAN} "Instalează pe acest PC (recomandat)"
LangString T_INSTALL_D ${LANG_ROMANIAN} "În folderul tău de utilizator, fără drepturi de administrator. Scurtături în meniul Start și pe desktop, dezinstalare din Setări Windows > Aplicații."
LangString T_PORTABLE ${LANG_ROMANIAN} "Portabil"
LangString T_PORTABLE_D ${LANG_ROMANIAN} "Totul într-un folder ales de tine (și pe un stick USB). Nu se scrie nimic în afara lui; ca să-l elimini, șterge folderul sau rulează Uninstall.exe din el."
LangString T_DESKTOP ${LANG_ROMANIAN} "Scurtătură pe desktop"
LangString T_STARTMENU ${LANG_ROMANIAN} "Scurtătură în meniul Start"
LangString T_EXISTING ${LANG_ROMANIAN} "Deja instalat: RenderBatch"
LangString T_DIR_P_TITLE ${LANG_ROMANIAN} "Folder portabil"
LangString T_DIR_P_SUB ${LANG_ROMANIAN} "Alege folderul în care vor sta RenderBatch, setările, presetările și modelele lui."
LangString T_NOWRITE ${LANG_ROMANIAN} "RenderBatch nu poate scrie în acest folder fără drepturi de administrator, iar setările și le ține în propriul folder. Alege un folder din folderul tău de utilizator sau de pe alt disc (de ex. D:\RenderBatch)."
LangString T_RUNNING ${LANG_ROMANIAN} "RenderBatch rulează. Închide-l, apoi apasă Reîncercare."
LangString T_COPYING ${LANG_ROMANIAN} "Se copiază aplicația..."
LangString T_FINISHING ${LANG_ROMANIAN} "Se finalizează instalarea: se obțin pachetele Python și modelele (se descarcă circa 250 MB dacă nu sunt pe acest PC)..."
LangString T_SETUP_LATER ${LANG_ROMANIAN} "RenderBatch e instalat, dar pachetele Python și modelele nu au putut fi descărcate (fără internet?). Pornește RenderBatch când ești online: termină atunci instalarea."
LangString T_RUN ${LANG_ROMANIAN} "Pornește RenderBatch"
LangString T_DEL_MINE ${LANG_ROMANIAN} "Ștergi și setările, presetările, aspectele, LUT-urile și modelele tale din acest folder?$\r$\n$\r$\nNu = le păstrezi (o instalare ulterioară în același folder le folosește din nou)."
